- name: Restart laclasse-publipostage
  service: name=laclasse-publipostage state=restarted
  notify: Check laclasse-publipostage

- name: Check laclasse-publipostage
  wait_for: port={{laclasse_publipostage_port}} delay=5 timeout=10
